package Policy_API.entity;

import java.util.UUID;

import org.springframework.data.annotation.Persistent;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotNull;

@Entity
@DynamoDBTable(tableName = "Policies")
@Persistent
public class Policy {
	@Id
    @DynamoDBAutoGeneratedKey 
    @DynamoDBHashKey(attributeName = "policyId")
    private String policyId;

	@NotNull
    @DynamoDBAttribute(attributeName = "Policy_Name")
    private String policyName;
	

	public String getPolicyId() {
		return policyId;
	}

	public void setPolicyId(String policyId) {
		this.policyId = policyId;
	}

	public String getPolicyName() {
		return policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}  

	public Policy(String policyId, @NotNull String policyName) {
		super();
		this.policyId = policyId;
		this.policyName = policyName;
	}
	
	public Policy() {
	    // Default constructor
	}
}
