package policy_api.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import jakarta.validation.constraints.NotNull;

@DynamoDBTable(tableName = "Policies")
public class Policy {
    @DynamoDBHashKey(attributeName = "policyId")
    @DynamoDBAutoGeneratedKey 
    private String policyId;

	@NotNull(message= "")
    @DynamoDBAttribute(attributeName = "Policy_Name")
    private String policyName;
	

	public String getPolicyId() {
		return policyId;
	}

	public void setPolicyId(String policyId) {
		this.policyId = policyId;
	}

	public String getPolicyName() {
		return policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}  

	public Policy(String policyId, @NotNull String policyName) {
		super();
		this.policyId = policyId;
		this.policyName = policyName;
	}
	
	public Policy() {
	    // Default constructor
	}
}
